### PR TITLE
Update readme to point at nasa/harmony-gdal-adapter

### PR DESCRIPTION
**Pull request by asjohnston-asf**
This adds a notice to the README to inform readers that the project is now maintained at nasa/harmony-gdal-adpater. I intent to [archive](https://docs.github.com/en/repositories/archiving-a-github-repository) this repository after this PR is merged.

@owenlittlejohns any feedback on language or formatting?

### CODE REVIEW

**Comment by owenlittlejohns** [comment]
Looks good to me! Particularly combined with archiving of the repository. The one possible question I have is whether users of your repository know that the ASF GDAL Subsetter is the same thing as the Harmony GDAL Adapter? (If it's mainly your development group, then I would guess the answer is "yes")

**Comment by asjohnston-asf** [comment]
I had the same thought. I considered "This project is now maintained...", is that any better?

**Comment by owenlittlejohns** [comment]
How about: "This project is now maintained as the Harmony GDAL Adapter at https://github.com/nasa/harmony-gdal-adapter"

**Comment by asjohnston-asf** [comment]
Or do we consider them separate projects? "This repository is no longer maintained. For

**Review by jhkennedy — APPROVED** [review]

**Pull request merged**
